import { registerCourseCategoriesBlock } from './course-categories/block';
import { registerCourseContents } from './course-content/block';
import { registerCourseCurriculum } from './course-curriculum/block';
import { registerCourseEnrollButtonBlock } from './course-enroll-button/block';
import { registerCourseFeatureImage } from './course-featured-image/block';
import { registerCourseHighlight } from './course-highlight/block';
import { registerCourseOverView } from './course-overview/block';
import { registerCoursePriceBlock } from './course-price/block';
import { registerCourseReviews } from './course-reviews/block';
import { registerCourseSearchForm } from './course-search-form/block';
import { registerCourseTitleBlock } from './course-title/block';
import { registerCoursesAuthorBlock } from './courses-author/block';
import { registerCourseStatsBlock } from './courses-stats/block';
import { registerCoursesBlock } from './courses/block';
import { initCSSGenerators } from './helpers/initCSSGenerators';
import { registerDeviceTypeStore } from './helpers/registerDeviceTypeStore';
import { updateBlocksCategoryIcon } from './helpers/updateBlocksCategoryIcon';
import { registerSingleCourse } from './single-course/block';

updateBlocksCategoryIcon();
registerDeviceTypeStore();
registerCoursesBlock();
registerCoursesAuthorBlock();
registerCoursePriceBlock();
registerCourseTitleBlock();
registerCourseEnrollButtonBlock();
registerCourseFeatureImage();
registerCourseOverView();
registerCourseCurriculum();
registerCourseHighlight();
registerCourseContents();
registerCourseReviews();
registerCourseSearchForm();
registerSingleCourse();
registerCourseCategoriesBlock();
registerCourseStatsBlock();
initCSSGenerators();
